### ISSUE TITLE
BST Lua problem. 

### ISSUE THREAD

**Issue by Galkapryme** [Headtatt/Gearswap#17]
When I load the "user_BST_gear" file, it appears broken (as compared to all the other job files). The HUD is not there, and when I run a simple macro command like "/console gs c cycle Weapons" the weapons do not change, and there is no output in the text window. I don't want BST to be the only job I have to use Vanilla macros on. Kindly assist.

**Comment by Headtatt** [comment]
No offense intended, but 99% of the time an issue of this sort is because of a typo or mistake made in the gearfile while adding your gear, an edit made to one of the files marked "do not edit", or an issue where one or more of the lib files isn't up to date.

Please consider visiting the discord server https://discord.gg/ug6xtvQ and opening a discussion in the #ffxi-support channel with your issue.

**Comment by Galkapryme** [comment]
I thought it might be a typo or something I did wrong on my end, so I updated the whole file via GitHub...same thing. I also tried just loading the author's file (i.e., Selindrile_Bst_gear.lua); same result. But I'll create a ticket via Discord.

**Comment by Galkapryme** [comment]
NOTE: I don't appear to have permissions to send a message in the FFXI-Support channel in Sel's Gearswap Support.

**Comment by Headtatt** [comment]
Yes, that's intentional. Look for a "create a thread" option.

**Comment by Bippin13** [comment]
> NOTE: I don't appear to have permissions to send a message in the FFXI-Support channel in Sel's Gearswap Support.

Create a thread as mike said or post in another channel to get started.

**Comment by Galkapryme** [comment]
Thank you both. I created a thread.
